(straight-use-package 'autothemer)
(require 'autothemer)

(autothemer-deftheme
 mytheme "My theme"

 ((((class color) (min-colors #xFFFFFF)))

  (mytx        "#efefef")
  (myoperator  "#bbb")
  (mybg        "#1e1e1e")
  (mykeyword   "DarkViolet")
  (myconstant  "DarkCyan")
  (mybuiltin   "DarkCyan")
  (mycomment   "#b11")
  (mydoc       "#f00")
  (mystring    "#e70")
  (myvar       "#da6")
  (mypropvar   "#57B")
  (myfunname   "#04f")
  (mytype      "#0A0")
  (mytypeparam "#6D0")
  (myparam     "#092")
  (mytab       "#282828")
  (myline      "#383838")
  (myregion    "#1d3854")
  (myhvars     "#070")
  (mynamespace "#05F")
  (mysearch    "Blue")
  (myjsdctype  "Red")
  (myjsdcval   "Red")
  (mywarning   "#b50")
  (mywstrail   "#800"))

 ((default                      (:foreground mytx :background mybg :height 170))
  (font-lock-comment-face       (:foreground mycomment))
  (font-lock-constant-face      (:foreground myconstant))
  (font-lock-builtin-face       (:foreground mybuiltin))
  (font-lock-function-name-face (:foreground myfunname))
  (font-lock-keyword-face       (:foreground mykeyword :weight 'bold))
  (font-lock-string-face        (:foreground mystring))
  (font-lock-variable-name-face (:foreground myvar))
  (font-lock-doc-face           (:foreground mydoc))
  (font-lock-type-face          (:foreground mytype))
  (isearch                      (:background mysearch :distant-foreground mytx))
  (js2-external-variable        ())
  (js2-function-param           (:foreground myparam))
  (js2-highlight-vars-face      (:background myhvars :distant-foreground mytx))
  (js2-warning                  (:underline  mywarning))
  (region                       (:background myregion))
  (lazy-highlight               (:background myregion))
  (whitespace-line              (:background myline :foreground nil))
  (whitespace-tab               (:background mytab))
  (whitespace-trailing          (:background mywstrail))
  (tree-sitter-hl-face:operator (:foreground myoperator))
  (tree-sitter-hl-face:variable.parameter (:foreground myvar))
  (tree-sitter-hl-face:variable (:foreground myvar))
  (tree-sitter-hl-face:function (:foreground myvar))
  (tree-sitter-hl-face:property (:foreground mytx))
  (tree-sitter-hl-face:property.definition (:foreground mytx))
  (tree-sitter-hl-face:function.call (:foreground mytx))
  (tree-sitter-hl-face:constructor (:foreground mynamespace))
  (tree-sitter-hl-face:type (:foreground mytype))
  (tree-sitter-hl-face:type.parameter (:foreground mytypeparam))
  (tree-sitter-hl-face:punctuation.special (:foreground mystring :weight 'bold))
  (tree-sitter-hl-face:attribute (:foreground mypropvar))
  (lsp-lsp-flycheck-info-unnecessary-face (:foreground nil :underline '(:style wave :color "ForestGreen")))
  (flymake-warning (:underline '(:style wave :color "#E70")))
  (eglot-highlight-symbol-face (:background "darkolivegreen"))
  (eglot-diagnostic-tag-unnecessary-face (:underline '(:style wave :color "#E70")))

  (vterm-color-black   (:foreground "#2E3436" :background "#555753"))
  (vterm-color-red     (:foreground "#CC0000" :background "#EF2929"))
  (vterm-color-green   (:foreground "#4E9A06" :background "#8AE234"))
  (vterm-color-yellow  (:foreground "#C4A000" :background "#FCE94F"))
  (vterm-color-blue    (:foreground "#3465A4" :background "#729FCF"))
  (vterm-color-magenta (:foreground "#75507B" :background "#AD7FA8"))
  (vterm-color-cyan    (:foreground "#06989A" :background "#34E2E2"))
  (vterm-color-white   (:foreground "#FFFFFF" :background "#FFFFFF"))))

(defface vterm-background '((t :background "#300A24")) "Background for vterm")

(provide-theme 'mytheme)
